@startuml

title __EXCEPTION's Class Diagram__\n

  package com.myself.nettychat {
    package com.myself.nettychat.common.exception {
      class ConnectionException {
          + ConnectionException()
      }
    }
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  package com.myself.nettychat {
    package com.myself.nettychat.common.exception {
      class NoFindHandlerException {
          + NoFindHandlerException()
      }
    }
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  ConnectionException +-down- PrintStreamOrWriter
  ConnectionException +-down- SentinelHolder
  ConnectionException +-down- WrappedPrintStream
  ConnectionException +-down- WrappedPrintWriter
  NoFindHandlerException +-down- PrintStreamOrWriter
  NoFindHandlerException +-down- SentinelHolder
  NoFindHandlerException +-down- WrappedPrintStream
  NoFindHandlerException +-down- WrappedPrintWriter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
